# Generated by Django 5.1.1 on 2024-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='register_status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
